export const productSeedData = [
  {
    name: "Classic Espresso",
    description: "Our signature espresso blend with rich flavor and smooth finish",
    image_url: "/placeholder.svg?height=300&width=300&text=Espresso",
    category: "coffee",
    price_min: 3.49,
    price_max: 4.99,
    sizes: [
      { value: "small", label: "Small (8oz)", price: 3.49 },
      { value: "medium", label: "Medium (12oz)", price: 3.99 },
      { value: "large", label: "Large (16oz)", price: 4.99 },
    ],
    options: [
      { value: "extra-shot", label: "Extra Shot", price_adjustment: 0.75 },
      { value: "vanilla", label: "Vanilla Syrup", price_adjustment: 0.5 },
      { value: "caramel", label: "Caramel Syrup", price_adjustment: 0.5 },
    ],
  },
  {
    name: "Cold Brew",
    description: "Smooth, cold-steeped coffee with low acidity",
    image_url: "/placeholder.svg?height=300&width=300&text=Cold+Brew",
    category: "coffee",
    price_min: 4.49,
    price_max: 5.99,
    sizes: [
      { value: "small", label: "Small (12oz)", price: 4.49 },
      { value: "medium", label: "Medium (16oz)", price: 4.99 },
      { value: "large", label: "Large (20oz)", price: 5.99 },
    ],
    options: [
      { value: "vanilla", label: "Vanilla Syrup", price_adjustment: 0.5 },
      { value: "caramel", label: "Caramel Syrup", price_adjustment: 0.5 },
      { value: "cream", label: "Sweet Cream", price_adjustment: 0.75 },
    ],
  },
  {
    name: "Blueberry Muffin",
    description: "Freshly baked muffin loaded with juicy blueberries",
    image_url: "/placeholder.svg?height=300&width=300&text=Blueberry+Muffin",
    category: "pastry",
    price_min: 3.29,
    price_max: 3.29,
    sizes: [{ value: "regular", label: "Regular", price: 3.29 }],
    options: [
      { value: "warmed", label: "Warmed", price_adjustment: 0 },
      { value: "butter", label: "Add Butter", price_adjustment: 0.25 },
    ],
  },
  {
    name: "Chocolate Croissant",
    description: "Flaky, buttery croissant filled with rich chocolate",
    image_url: "/placeholder.svg?height=300&width=300&text=Chocolate+Croissant",
    category: "pastry",
    price_min: 3.99,
    price_max: 3.99,
    sizes: [{ value: "regular", label: "Regular", price: 3.99 }],
    options: [{ value: "warmed", label: "Warmed", price_adjustment: 0 }],
  },
  {
    name: "Caramel Macchiato",
    description: "Espresso with steamed milk and caramel drizzle",
    image_url: "/placeholder.svg?height=300&width=300&text=Caramel+Macchiato",
    category: "coffee",
    price_min: 4.29,
    price_max: 5.79,
    sizes: [
      { value: "small", label: "Small (8oz)", price: 4.29 },
      { value: "medium", label: "Medium (12oz)", price: 4.79 },
      { value: "large", label: "Large (16oz)", price: 5.79 },
    ],
    options: [
      { value: "extra-shot", label: "Extra Shot", price_adjustment: 0.75 },
      { value: "extra-caramel", label: "Extra Caramel", price_adjustment: 0.5 },
      { value: "almond-milk", label: "Almond Milk", price_adjustment: 0.75 },
    ],
  },
]
